const keywordRelevance = {
  ghana: 5,
  accra: 4,
  dies: 5,
  dead: 5,
  death: 5,
  obituary: 5,
  breaking: 4,
  earthquake: 5,
  explosion: 5,
  fire: 5,
  flood: 5,
  drought: 5,
  accident: 4,
  crime: 4,
  investigation: 4,
  arrest: 4,
  trial: 4,
  verdict: 4,
  sentence: 4,
  appeal: 3,
  election: 5,
  galamsey: 5,
  economy: 5,
  corruption: 4,
  inflation: 4,
  unemployment: 4,
  education: 4,
  healthcare: 4,
  infrastructure: 4,
  policy: 3,
  development: 4,
  investment: 4,
  diplomacy: 4,
  security: 4,
  defence: 5,
  energy: 5,
  agriculture: 4,
  tourism: 4,
  trade: 4,
  industry: 5,
  protest: 4,
  strike: 4,
  scandal: 5,
  resignation: 4,
  appointment: 3,
  announcement: 3,
  'policy change': 3,
  legislation: 4,
  judiciary: 4,
  constitution: 4,
  'human rights': 5,
  'press freedom': 4,
  media: 4,
  sports: 4,
  culture: 4,
  tradition: 4,
  festival: 3,
  'natural disaster': 5,
  'international relations': 4,
  'foreign policy': 4,
  Commonwealth: 4,
  ECOWAS: 4,
  'United Nations': 3,
  summit: 3,
  conference: 3,
  visit: 3,
  meeting: 3,
  agreement: 3,
  deal: 3,
  contract: 3,
  merger: 3,
  acquisition: 3,
  launch: 3,
  initiative: 3,

  // Political figures
  'Alan Kyerematen': 5,
  'Mahamudu Bawumia': 5,
  'Nana Akufo-Addo': 5,
  'John Dramani Mahama': 5,
  'John Mahama': 5,
  JM: 5,
  'Akuffo Addo': 5,
  Bawumia: 5,
  'Kennedy Agyapong': 5,
  'Osei Kyei Mensah Bonsu': 3,
  'Asiedu Nketia': 5,
  'NPP General Secetary': 5,
  'NDC General Secetary': 5,
  'Justin Frimpong Kodua': 5,
  'Kwaku Agyemang-Manu': 4,
  'Kojo Oppong Nkrumah': 4,
  'Ambrose Dery': 4,
  'Shirley Ayorkor Botchwey': 4,
  'Ken Ofori-Atta': 5,
  'Dominic Aduna Bingab Nitiwul': 4,
  'Matthew Opoku Prempeh': 4,
  'Kwaku Afriyie': 4,
  'Ursula Owusu-Ekuful': 4,
  'Francis Asenso-Boakye': 4,
  'Kwasi Amoako-Attah': 4,
  'Cassiel Ato Forson': 5,
  'John Abdulai Jinapor': 5,
  'Dominic Akuritinga Ayine': 4,
  'Kwame Governs Agbodza': 4,
  'Eric Opoku': 4,
  'Agnes Naa Momo Lartey': 4,
  'Abla Dzifa Gomashie': 4,
  'Emelia Arthur': 4,
  'George Opare-Addo': 4,
  'Haruna Iddrisu': 4,
  'Ahmed Ibrahim': 4,
  'Elizabeth Ofosu Adjare': 4,
  'Edward Omane Boamah': 4,
  'Samuel Nartey George': 4,
  'Emmanuel Armah-Kofi Buah': 4,
  'Kofi Iddie Adams': 4,
  'Abdul-Rashid H. Pelpuo': 4,
  'Kwabena Mintah Akandoh': 4,
  'Ibrahim Murtala Muhammed': 4,
  'Joseph Bukari Nikpe': 4,
  'Muntaka Mohammed-Mubarak': 4,
  'Samuel Okudzeto Ablakwa': 4,
  'Adjei Kenneth Gilbert': 4,
  'Emmanuel Kwadwo Agyekum': 4,
  'Felix Kwakye Ofosu': 4,
  'Issifu Seidu': 4,
  'Puozuing Charles Lwanga': 3,
  'Joseph Addae Akwaboa': 3,
  'Francis Owusu Antwi': 3,
  'Wilbert Petty Brentum': 3,
  'Eduamoah Ekow Panyin Okyere': 3,
  'Joseph Nelson': 3,
  'Ali Adolf John': 3,
  'John Kwadwo Gyapong': 3,
  'James Gunu': 3,
  'Rita Akosua Adjei Awatey': 3,
  'Ibrahim Tia': 3,
  'Frank Amoakohene': 3,
  'Akamugri Donatus Atanga': 3,
  'Charity Gardiner': 3,
  'Salisu Be-Awuribe': 3,
  'Linda Ocloo': 3,

  // Government Institutions
  'Jubilee House': 5,
  'State House': 5,
  Parliament: 5,
  'Ghana Armed Forces': 5,
  Military: 5,
  'Supreme Court': 5,
  Court: 5,
  Judiciary: 5,
  Judicial: 3,
  Soldiers: 3,
  'Judicial Council': 3,
  'Judicial Service Commission': 3,
  Policy: 4,
  NPP: 5,
  NDC: 5,
  'New Patriotic Party': 5,
  'National Democratic Congress': 5,
  'Parliamentary Service': 4,
  'Ghana Immigration Service': 4,
  'Ghana Prisons Service': 4,
  COCOBOD: 5,
  GOLDBOD: 4,
  Majority: 5,
  Minority: 5,
  'Ministry of Defence': 4,
  'National Fire Service': 4,
  'Judicial Service': 5,
  'Council of State': 3,
  'Ghana Bar Association': 4,
  'National Security': 4,
  'Ghana Police Service': 5,
  'Bureau of National Investigation': 4,
  'Bank of Ghana': 5,
  'National Health Insurance Authority': 3,
  'Ministry of Energy': 4,
  'Ghana Standards Authority': 3,
  'Ministry of Railways Development': 3,
  'Veterans Association of Ghana': 3,
  'Office of the Head of Civil Service': 3,
  'Ministry of Tourism, Arts & Culture': 3,
  'Korle Bu Teaching Hospital': 4,
  'Ghana Postal Services': 3,
  'Ministry of Health': 5,
  'National Council for Tertiary Education': 3,
  'Ghana Shippers Council': 3,
  'Greater Accra Regional Hospital': 4,
  'National Ambulance Service': 3,
  'Public Service Commission': 3,
  'Council for Scientific & Industrial Research': 3,
  'Ghana National Association of Teachers': 3,
  'Nurses and Midwifery Council': 3,
  'Ghana Tourism Authority': 3,
  'National Commission on Culture': 3,
  'Ghana Health Service': 5,
  'National Disaster Management Organization': 4,
  'National Service Secretariat': 3,
  'Ministry of Youth and Sports': 3,
  'Ghana Airport Company': 3,
  'Volta River Authority': 3,
  'National Petroleum Authority': 3,
  'Public Procurement Authority': 3,
  'Ghana Broadcasting Corporation': 4,
  'Trust Hospital': 3,
  'Ghana Revenue Authority': 4,
  'Food and Drugs Authority': 4,
  'Ghana Cocoa Board': 4,
  'Ghana Free Zones Authority': 3,
  'Ghana Ports and Harbours Authority': 3,
  'National Communications Authority': 3,
  'Ghana Meteorological Agency': 3,
  'Ghana Statistical Service': 3,
  'National Peace Council': 3,
  'National Tripartite Committee': 3,
  Dumsor: 5,

  // Ministries (deduplicated)
  'Ministry of Finance': 5,
  'Ministry of the Interior': 5,
  'Ministry of Foreign Affairs and Regional Integration': 5,
  'Ministry of Foreign Affairs': 5,
  'National Security': 5,
  'Ministry of National Security': 5,
  'Ministry of Justice': 5,
  'Ministry of Energy': 5,
  'Ministry of Justice and Attorney General': 5,
  'Attorney General': 5,
  'Ministry of Trade and Industry': 3,
  'Ministry of Employment and Labour Relations': 3,
  'Ministry of Local Government and Rural Development': 3,
  'Ministry of Roads and Highways': 4,
  'Ministry of Transport': 3,
  'Ministry of Communications': 4,
  'Ministry of Environment, Science, Technology and Innovation': 3,
  'Ministry of Water Resources, Works and Housing': 3,
  'Ministry of Food and Agriculture': 3,
  'Ministry of Fisheries and Aquaculture Development': 2,
  'Ministry of Lands and Natural Resources': 3,
  'Ministry of Tourism, Arts and Culture': 3,
  'Ministry of Education': 5,
  'Ministry of Gender, Children and Social Protection': 2,
  'Ministry of National Security': 4,
  'Ministry of Health': 5,
  'Ministry of Health and Sanitation': 5,

  'National Health Insurance Authority': 5,
  'National Health Insurance': 5,
  'National Health Insurance Scheme': 5,
  'National Health Insurance Fund': 5,
  'Free Senior High School': 5,
  'Free SHS': 5,
  'National Health Insurance Scheme': 5,
  'Ghana Card': 5,
  'E-Levy Policy': 5,
  'E-Levy': 5,
  'Covid Levy': 5,
  'Covid-19 Levy': 5,
  'Covid-19': 5,
  AIDS: 4,
  'Mahama cares': 4,
  'Ghana CARES “Obaatan Pa” Programme': 4,
  'Agenda 111': 4,
  'Planting for Food and Jobs': 4,
  'One District One Factory': 4,
  'National Digitalisation Agenda': 4,
  'Public Financial Management Reform': 4,
  'National Service Policy': 4,
  'Livelihood Empowerment Against Poverty': 4,
  'YouStart Initiative': 3,
  'Digital Property Addressing System': 3,
  'National Youth Employment Programme': 3,
  'One Village One Dam': 3,
  'Ghana Beyond Aid': 3,
  'National Entrepreneurship and Innovation Programme': 3,
  'Ghana School Feeding Programme': 3,
  'Free Primary Healthcare': 3,
  'National Rental Assistance Scheme': 3,
  'National Energy Transition Framework': 3,
  'Cybersecurity Policy and Strategy': 3,
  'National Climate Change Policy': 3,
  'Local Government Decentralisation Policy': 3,
  'National Sanitation Campaign': 3,
  'Teacher Licensure Policy': 3,
  'TVET Transformation Programme': 3,
  'Youth in Agriculture Programme': 3,
  'National Financial Inclusion and Development Strategy': 3,
  'Zongo Development Fund': 2,
  'Tax Stamp Policy': 2,
  'Rural Electrification Project': 2,
  'Land Tenure Policy': 2,
  'Gender Equality Policy': 2,
  'National Tourism Development Plan': 2,
  'Fisheries and Aquaculture Development Plan': 2,
  'Free Wifi for SHS and Public Universities': 2,
  'National Transport Policy': 2,

  'Bank of Ghana': 5,
  'Electoral Commission of Ghana': 5,
  'Ghana Police Service': 5,
  'National Identification Authority': 5,
  'National Communications Authority': 5,

  'Ghana Water Company Limited': 4,
  'Volta River Authority': 4,
  'Ghana Grid Company': 4,
  'Ghana Education Service': 4,
  'National Petroleum Authority': 4,
  'Social Security and National Insurance Trust': 4,
  'National Disaster Management Organisation': 4,
  'Ghana National Fire Service': 4,
  'National Service Secretariat': 4,
  'Food and Drugs Authority': 4,
  'National Health Insurance Authority': 4,

  'Ghana Immigration Service': 3,
  'Ghana Statistical Service': 3,
  'Ghana Ports and Harbours Authority': 3,
  'Ghana Civil Aviation Authority': 3,
  'Ghana Atomic Energy Commission': 3,
  'Driver and Vehicle Licensing Authority': 3,
  'Ghana Tourism Authority': 3,
  'Ghana Investment Promotion Centre': 3,
  'Ghana Shippers Authority': 3,
  'Ghana Post': 3,

  'Public Utilities Regulatory Commission': 2,
  'Energy Commission': 2,
  'National Road Safety Authority': 2,
  'Environmental Protection Agency': 2,
  'Ghana Export Promotion Authority': 2,
  'Lands Commission': 3,
  'Gaming Commission of Ghana': 2,
  'Ghana Railway Development Authority': 2,
  'Ghana Cocoa Board': 4,

  'Ghana Free Zones Authority': 1,
  'Ghana Broadcasting Corporation': 1,
  'Centre for Scientific and Industrial Research': 1,
  'Ghana Standards Authority': 1,
  'Ghana News Agency': 1,
};

module.exports = keywordRelevance;
